// main
var CELL_SIZE = 12;
var XSIZE = Math.floor(800/CELL_SIZE);
var YSIZE = Math.floor(600/CELL_SIZE);

var NORTH = 0;
var EAST = 1;
var SOUTH = 2;
var WEST = 3;

var GAME_LIFE_TIME = 1000000;
var UPDATE_PERIOD = 100;

// mound
var INIT_ANTS = 10;

// ant
var EXPLORE = 0;
var EXPLOIT = 1;
var LAY_EGG = 2;

var LAY_TIME = 100;
var MIN_LAY_TIME = 10;

var FORAGE_WEIGHT = 5;
var BREED_WEIGHT = 100;

var DEATH_AGE = 0;
var DEATH_HUNGER = 1;

var CHANCE_TO_DIE = 0.001;
var HUNGER_THRESHHOLD = 500;
var EAT_AMOUNT = 10;
var MUTATION_RATE = 0.05;
var MAX_DEVIATION = 0.1;

var OUTBOUND = 0;
var INBOUND = 1;

var MAX_ENERGY = 500;
var MIN_ENERGY = 50;
var MAX_ANT_FOOD = 20;
var MIN_ANT_FOOD = 2;
var ENERGY_DECAY = 5;

// larva

var MATURE_TIME = 100;

//tile
var MAX_PHEROMONE = MAX_ENERGY;
var MULT = Math.ceil(MAX_PHEROMONE/10);
var DECAY_RATE = Math.ceil(MAX_PHEROMONE/200);
var MAX_TILE_FOOD = 10000;
var FOOD_ABUNDANCE = 0.01;
var FOOD_REGEN_AMOUNT = 1000;
var FOOD_REPLENISH_AMOUNT = 500;
var FOOD_REGEN_RATE = 0.0001;
var FOOD_REPLENISH_RATE = 0.25;
